### PR TITLE
Made SauceNao class implementing PySauceNao package

### PR DESCRIPTION
**Pull request by Manicarus**
Since PySauceNao uses asynchronous functions, it might be useful to import syncer packages.

I haven't realized until making a pull request that the original author was working on booru packages. I agree that using python-written APIs is a better approach. Seems like other developers already made python APIs for Gelbooru and Szurubooru. But sadly I haven't found APIs for Sankaku Complex

  - [FujiMakoto/PyGelboru ](https://github.com/FujiMakoto/pygelbooru)
  - [sgsunder/python-szurubooru](https://github.com/sgsunder/python-szurubooru)

I uploaded classes/scraper packages just in case but once finishing working on classes/booru packages, they will be deprecated and be ready for removal.

### CODE REVIEW

**Comment by reluce** [comment]
Hey there, thanks for contributing!

This branch is pretty scuffed since I made it in a hurry because IQDB was down during that time. I wanted to keep working on it, but as soon as IQDB was working again, I didn't bother with it.

The class saucenao.py never gets actually called in auto_tagger.py, so I'm not sure if your changes are even getting executed. Or am I overlooking something?
As soon as they are implemented in the main class, I can go ahead and merge them. After that we can see if we can implement any other modules and rework the scrapers. I don't have much time at the moment, so you can go ahead and take a look if you'd like.

Just for context:

In auto_tagger.py I use the SauceNAO Python Module: https://pypi.org/project/saucenao-api/
First, the script searches Danbooru for the MD5 hash of the file. If there is no results, it queries SauceNAO. But even then, it just searches the results for a Danbooru URL and uses that. Then, danbooru.py gets called which uses the pybooru module. As you said, using existing modules for each boorus would be great. Aggregating tags from each matching SauceNAO result is also a good idea.

Sankaku's API is unavailable, so working with HTML seems like the only choice for now.

I also pushed a deepbooru branch which I was working on some time ago (well, I was just copy pasting stuff so it somehow worked lol). Using SauceNAO + DeepBooru as a fallback would be great in the future.

**Comment by Manicarus** [comment]
Hello, thank you for the feedback.

Actually I deliberately avoided making changes to the main function so that I don't accidentally break anything. However, I can see your point that I should illustrate and thus prove that SauceNao class is working properly. I'll make some updates and let you know. 

A bit off-topic but have you considered making the whole project installable using pip?
Following is what I have in mind. 
I am working on it under packaging branch. 
Executable names can be changed in the future.

``` bash
python -m pip install szurutoolkit # install szurutoolkit package
szuru-upload --source /path/to/images # upload images at /path/to/images
szuru-autotag 81 # autotag post id 81
```

Seems like I am gonna have to move auto_tagger.py and image_uploader.py to different location other than the root of the project. Under my package branch, the files are placed under tools directory. 

If it's not something you prefer, then I won't make pull requests for it.

**Comment by Manicarus** [comment]
I updated auto_tagger.py implementing the SauceNao class. However, I should point out that I completely rewrote how main function works. There are few differences that I should mention:
 - UserInput class reads configuration file in json format
 - API.get_post method supplies byte images to Post instances. 

Since I have no confident skill in parsing json files, I reused configparser from old commits. If you prefer using json files I'll look into it.

SauceNao.get_result method tries at first to get results by uploading images from URL and falls back to getting results by uploading images from local drive if szurubooru server isn't accessible from the Internet. So in my case, downloading images and resizing images is done in SauceNao.get_result method. Again this time, I brought back old API.get_post method just for now, renamed in API.get_post_old.

**Comment by reluce** [comment]
Can you change the restriction for edits in your pull request? After that I can commit my changes so you can have a look at it.

I made following changes:
-  Introduce modules PyGelbooru and PyBooru
-  Reintroduce parameter --sankaku_url in main function
-  Make statistics more accurate
-  Immediately tag posts in szuru instead of queuing
-  Implement better handling of SauceNao limits
-  Implement better handling of the tagme tag
-  Remove double functions in saucenao.py and api.py
-  First draft of pixiv module (login is currently broken)
-  Change how SauceNao results are being detected in for loop
-  Update requirements.txt
-  Update user_input.py and add sample config.json

Some things are completely unrelated to the pull requests, but before I knew I already changed too much without committing.

Some things to note:

> SauceNao.get_result method tries at first to get results by uploading images from URL and falls back to getting results by uploading images from local drive if szurubooru server isn't accessible from the Internet.

I changed it so it looks only at the variable szuru_public. In this case we don't have to waste an extra request every single time.

>-  Change how SauceNao results are being detected in for loop

During my testing the results from the pysaucenao module were quiet weird. If I search my image on the GUI directly, it returns every match with URLs (various Boorus, pixiv etc.). But as soon as I use the module, only a few of those were being returned. E.g. it found an index for yande.re, but returned a Danbooru URL while Danbooru wasn't even in the index. Going by the url instead of the index seems to be more reliable.

>-  Immediately tag posts in szuru instead of queuing

When uncaught exceptions are occuring while the script is running, it just quits and our posts won't get tagged in szuru. Can be a bit frustrating when have a larger batch of posts to tag.

The main function probably needs some additional work. Maybe using async for the set_meta_data function would be useful, so  the script can continue searching SauceNao while tagging the previous post in szuru.

>A bit off-topic but have you considered making the whole project installable using pip?
I am working on it under packaging branch. Executable names can be changed in the future.

That would be very useful.  Before that I want to merge the SauceNao branch to master while also implementing the DeepBooru feature. After that we can have a look at it again 👍🏻 .

**Comment by Manicarus** [comment]
Sorry about my lagging response. I'll be working on it and let you know after I am done.

**Comment by reluce** [comment]
I already did every change I mentioned in my comment, no worries.
But true, the scope of that is way bigger than just implementing the pysaucenao module.

I will close this pull request and just commit your and my changes since I pulled your request before working on top of it.

Let me know if you have any other suggestions.

**Pull request closed without merging**
